//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainVvodVivod
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainDemEntities2 : DbContext
    {
        public static TrainDemEntities2 _context;
        public TrainDemEntities2()
            : base("name=TrainDemEntities2")
        {
        }

        public static TrainDemEntities2 GetContext()
        {
            if (_context == null)
                _context = new TrainDemEntities2();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Лист1_> Лист1_ { get; set; }
    }
}
