//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainVvodVivod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Лист1_
    {
        public string Отчество { get; set; }
        public string Почта { get; set; }
        public Nullable<System.DateTime> дата_рождения { get; set; }
        public Nullable<double> страна { get; set; }
        public Nullable<double> телефон { get; set; }
        public string пароль { get; set; }
        public string пол { get; set; }
        public double Id { get; set; }
    }
}
